[package]

name = "yasteroids"
version = "0.3.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[features]
default = []

[dependencies]
cgmath = "0.8"
gfx = "0.12"
gfx_window_glutin = "0.12"
glutin = "0.6"
pegasus = "0.2"
rand = "0.3"
specs = "0.7.1"
