[package]

name = "yasteroids"
version = "0.2.0"
authors = [
"Dzmitry Malyshau <kvarkus@gmail.com>",
]

[features]
default = []

[dependencies]
env_logger = "*"
rand = "*"
time = "*"
cgmath = "0.8"
specs = "0.6"
gfx = "0.11"
gfx_window_glutin = "0.11"
glutin = "0.5"
